# Generated by Django 6.0.1 on 2026-01-31 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='requests_xls/', verbose_name='Исходный файл заказа')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Запрос на расчет',
                'verbose_name_plural': 'Запросы на расчет',
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название (например, 40HQ)')),
                ('length_mm', models.PositiveIntegerField(verbose_name='Длина (мм)')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Ширина (мм)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Высота (мм)')),
                ('max_weight_kg', models.PositiveIntegerField(verbose_name='Макс. вес (кг)')),
                ('volume_m3', models.FloatField(verbose_name='Полезный объем (м3)')),
            ],
            options={
                'verbose_name': 'Тип контейнера',
                'verbose_name_plural': 'Типы контейнеров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('item_length_mm', models.PositiveIntegerField(verbose_name='Длина товара (мм)')),
                ('item_width_mm', models.PositiveIntegerField(verbose_name='Ширина товара (мм)')),
                ('item_height_mm', models.PositiveIntegerField(verbose_name='Высота товара (мм)')),
                ('item_weight_kg', models.FloatField(verbose_name='Вес товара (кг)')),
                ('pallet_length_mm', models.PositiveIntegerField(verbose_name='Длина паллеты (мм)')),
                ('pallet_width_mm', models.PositiveIntegerField(verbose_name='Ширина паллеты (мм)')),
                ('pallet_height_mm', models.PositiveIntegerField(verbose_name='Высота паллеты с грузом (мм)')),
                ('items_per_pallet', models.PositiveIntegerField(verbose_name='Кол-во товаров на паллете')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Опасный груз')),
                ('is_stackable', models.BooleanField(default=True, verbose_name='Можно штабелировать')),
                ('can_be_unpalletized', models.BooleanField(default=False, verbose_name='Можно распалечивать')),
                ('items_per_masterbox', models.PositiveIntegerField(default=1, verbose_name='Штук в мастербоксе')),
                ('moq', models.PositiveIntegerField(default=1, verbose_name='Min кол-во заказа (MOQ)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PackingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.PositiveIntegerField()),
                ('total_weight_kg', models.FloatField(verbose_name='Вес груза (кг)')),
                ('total_volume_m3', models.FloatField(verbose_name='Объем груза (м3)')),
                ('volume_utilization_percent', models.FloatField(verbose_name='Заполнение по объему (%)')),
                ('area_utilization_percent', models.FloatField(verbose_name='Заполнение по полу (%)')),
                ('packing_layout', models.JSONField(default=dict, verbose_name='Схема расстановки (JSON)')),
                ('calculation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='logistics.calculationrequest')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.containertype')),
            ],
            options={
                'verbose_name': 'Результат (Контейнер)',
                'verbose_name_plural': 'Результаты (Контейнеры)',
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('calculation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.calculationrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Товар')),
            ],
        ),
    ]
