# Generated by Django 6.0.1 on 2026-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
