# Generated by Django 6.0.1 on 2026-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_height_mm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_length_mm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_width_mm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='items_per_masterbox',
        ),
        migrations.RemoveField(
            model_name='product',
            name='items_per_pallet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq',
        ),
        migrations.AddField(
            model_name='product',
            name='battery_flag',
            field=models.BooleanField(default=False, verbose_name='Battery'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='eol_flag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EOL'),
        ),
        migrations.AddField(
            model_name='product',
            name='gz_flag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GZ'),
        ),
        migrations.AddField(
            model_name='product',
            name='kj_flag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='k/j'),
        ),
        migrations.AddField(
            model_name='product',
            name='masterbox_height_mm',
            field=models.FloatField(default=0, verbose_name='Height Masterbox (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='masterbox_length_mm',
            field=models.FloatField(default=0, verbose_name='Length Masterbox (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='masterbox_width_mm',
            field=models.FloatField(default=0, verbose_name='Width Masterbox (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_requirement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order requirement'),
        ),
        migrations.AddField(
            model_name='product',
            name='pallet_weight_kg',
            field=models.FloatField(default=0, verbose_name='Pallet Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_height_mm',
            field=models.FloatField(default=0, verbose_name='Height Products (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_length_mm',
            field=models.FloatField(default=0, verbose_name='Length Products (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_width_mm',
            field=models.FloatField(default=0, verbose_name='Width Products (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_of_masterbox',
            field=models.PositiveIntegerField(default=1, verbose_name='Qty of master box'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_of_pallet',
            field=models.PositiveIntegerField(default=1, verbose_name='Qty of pallet'),
        ),
        migrations.AddField(
            model_name='product',
            name='si_flag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SI'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spec-n Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='can_be_unpalletized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Можно распалечивать'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_dangerous',
            field=models.BooleanField(blank=True, null=True, verbose_name='Опасный груз'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_stackable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Можно штабелировать'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_height_mm',
            field=models.FloatField(default=0, verbose_name='Height Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_length_mm',
            field=models.FloatField(default=0, verbose_name='Length Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_width_mm',
            field=models.FloatField(default=0, verbose_name='Width Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
