# Generated by Django 6.0.1 on 2026-02-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_product_item_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='masterbox_weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес мастербокса (кг)'),
        ),
    ]
