# Generated by Django 6.0.1 on 2026-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_product_masterbox_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='masterbox_height_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Height Masterbox (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='masterbox_length_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Length Masterbox (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='masterbox_width_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Width Masterbox (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_height_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Height Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_length_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Length Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_weight_kg',
            field=models.FloatField(default=0, null=True, verbose_name='Pallet Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_width_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Width Pallet (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Height Products (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Length Products (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width_mm',
            field=models.FloatField(default=0, null=True, verbose_name='Width Products (mm)'),
        ),
    ]
