# Generated by Django 5.2.12 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_product_masterbox_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В очереди'), ('PROCESSING', 'Рассчитывается'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery'),
        ),
        migrations.AddField(
            model_name='packingresult',
            name='products',
            field=models.JSONField(default=list, verbose_name='Список товаров в контейнере'),
        ),
        migrations.AlterField(
            model_name='calculationrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packingresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packingresult',
            name='packing_layout',
            field=models.JSONField(default=list, verbose_name='Схема расстановки (JSON)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
