# Generated by Django 5.2.12 on 2026-07-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_calculationrequest_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/', verbose_name='Файл раскладки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('calculation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export', to='logistics.calculationrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл раскладки',
                'verbose_name_plural': 'Файлы раскладок',
            },
        ),
    ]
