version: '3.8'

services:
  db:
    image: postgres:15
    container_name: logistics_db
    restart: always
    environment:
      - POSTGRES_DB=logistics_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: logistics_redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: logistics_api
    command: > 
      sh -c "python manage.py makemigrations && python manage.py migrate && 
      gunicorn ContainerPlanner.wsgi:application -c gunicorn.conf.py"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ContainerPlanner.settings
      - DB_HOST=db
      - DB_NAME=logistics_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: .
    container_name: logistics_celery
    command: celery -A ContainerPlanner worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=ContainerPlanner.settings
      - DB_HOST=db
      - DB_NAME=logistics_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: logistics_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Подкидываем наш конфиг
      - prometheus_data:/prometheus # Сохраняем историю метрик
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: logistics_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Пароль для входа (логин тоже admin)
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: logistics_pg_exporter
    environment:
      # Подключаемся к нашей БД для сбора метрик
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/logistics_db?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: logistics_node_exporter
    ports:
      - "9100:9100"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: logistics_frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
